/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-05-26 01:30:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/head.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Portfolio Section-->\r\n");
      out.write("        <section class=\"page-section portfolio\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Portfolio Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Portfolio</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Portfolio Grid Items-->\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <!-- Portfolio Item 1-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal1\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"../assets/img/portfolio/cabin.png\" alt=\"...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 2-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal2\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"../assets/img/portfolio/cake.png\" alt=\"...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 3-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal3\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"../assets/img/portfolio/circus.png\" alt=\"...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 4-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal4\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"../assets/img/portfolio/game.png\" alt=\"...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 5-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5 mb-md-0\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal5\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"../assets/img/portfolio/safe.png\" alt=\"...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 6-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal6\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"../assets/img/portfolio/submarine.png\" alt=\"...\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- About Section-->\r\n");
      out.write("        <section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- About Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-white\">About</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- About Section Content-->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 ms-auto\"><p class=\"lead\">Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional SASS stylesheets for easy customization.</p></div>\r\n");
      out.write("                    <div class=\"col-lg-4 me-auto\"><p class=\"lead\">You can create your own custom avatar for the masthead, change the icon in the dividers, and add your email address to the contact form to make it fully functional!</p></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- About Section Button-->\r\n");
      out.write("                <div class=\"text-center mt-4\">\r\n");
      out.write("                    <a class=\"btn btn-xl btn-outline-light\" href=\"https://startbootstrap.com/theme/freelancer/\">\r\n");
      out.write("                        <i class=\"fas fa-download me-2\"></i>\r\n");
      out.write("                        Free Download!\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      	\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        <!-- Portfolio Modals-->\r\n");
      out.write("        <!-- Portfolio Modal 1-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" aria-labelledby=\"portfolioModal1\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Log Cabin</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"../assets/img/portfolio/cabin.png\" alt=\"...\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 2-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" aria-labelledby=\"portfolioModal2\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Tasty Cake</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"../assets/img/portfolio/cake.png\" alt=\"...\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 3-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" aria-labelledby=\"portfolioModal3\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Circus Tent</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"../assets/img/portfolio/circus.png\" alt=\"...\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 4-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" aria-labelledby=\"portfolioModal4\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Controller</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"../assets/img/portfolio/game.png\" alt=\"...\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 5-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" aria-labelledby=\"portfolioModal5\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Locked Safe</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"../assets/img/portfolio/safe.png\" alt=\"...\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 6-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" aria-labelledby=\"portfolioModal6\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                    <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Submarine</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"../assets/img/portfolio/submarine.png\" alt=\"...\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-4\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-xmark fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <!-- * *                               SB Forms JS                               * *-->\r\n");
      out.write("        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\r\n");
      out.write("        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\r\n");
      out.write("        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
