/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-05-26 02:49:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/footer.jsp", Long.valueOf(1685062313123L));
    _jspx_dependants.put("/include/head.jsp", Long.valueOf(1685066223607L));
    _jspx_dependants.put("/include/header.jsp", Long.valueOf(1685062771660L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write(" <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Freelancer - Start Bootstrap Theme</title>\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"../css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("        <script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.7.0.js\"\r\n");
      out.write("  integrity=\"sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write(" </head>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\" id=\"mainNav\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#page-top\">Start Bootstrap</a>\r\n");
      out.write("                <button class=\"navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    Menu\r\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"loginpage.mem\">로그인</a></li>\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"list.crud\">CRUD 연습 (마지막)</a></li>\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded\" href=\"#contact\">혼자연습</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Masthead-->\r\n");
      out.write("  <header class=\"masthead bg-primary text-white text-center\">\r\n");
      out.write("            <div class=\"container d-flex align-items-center flex-column\">\r\n");
      out.write("                <!-- Masthead Avatar Image-->\r\n");
      out.write("                <img class=\"masthead-avatar mb-5\" src=\"assets/img/avataaars.svg\" alt=\"...\" />\r\n");
      out.write("                <!-- Masthead Heading-->\r\n");
      out.write("                <h1 class=\"masthead-heading text-uppercase mb-0\">Start Bootstrap</h1>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Masthead Subheading-->\r\n");
      out.write("                <p class=\"masthead-subheading font-weight-light mb-0\">Graphic Artist - Web Designer - Illustrator</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("     <!-- Contact Section-->\r\n");
      out.write("        <section class=\"page-section\" id=\"contact\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Contact Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">로그인</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Contact Section Form-->\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-lg-8 col-xl-7\">\r\n");
      out.write("                        <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                        <!-- * * SB Forms Contact Form * *-->\r\n");
      out.write("                        <!-- * * * * * * * * * * * * * * *-->\r\n");
      out.write("                        <!-- This form is pre-integrated with SB Forms.-->\r\n");
      out.write("                        <!-- To make this form functional, sign up at-->\r\n");
      out.write("                        <!-- https://startbootstrap.com/solution/contact-forms-->\r\n");
      out.write("                        <!-- to get an API token!-->\r\n");
      out.write("                        <form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\r\n");
      out.write("                            <!-- id input-->\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input class=\"form-control\" name=\"id\" id=\"userid\" type=\"text\" placeholder=\"id를 입력하세요\" data-sb-validations=\"required\" />\r\n");
      out.write("                                <label for=\"name\">아이디</label>\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"name:required\">아이디 필수입력</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- pw input-->\r\n");
      out.write("                            <div class=\"form-floating mb-3\">\r\n");
      out.write("                                <input class=\"form-control\" name=\"pw\" id=\"userpw\" type=\"email\" placeholder=\"pw 입력\" data-sb-validations=\"required\" />\r\n");
      out.write("                                <label for=\"email\">패스워드</label>\r\n");
      out.write("                                <div class=\"invalid-feedback\" data-sb-feedback=\"email:required\">패스워드 필수입력</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          \r\n");
      out.write("                            \r\n");
      out.write("                          \r\n");
      out.write("                                  <a class=\"btn btn-primary btn-xl\" onclick=\"login();\">로그인</a>\r\n");
      out.write("                   \r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("  	");
      out.write("\r\n");
      out.write("  <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer text-center\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Footer Location-->\r\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Location</h4>\r\n");
      out.write("                        <p class=\"lead mb-0\">\r\n");
      out.write("                            2215 John Daniel Drive\r\n");
      out.write("                            <br />\r\n");
      out.write("                            Clark, MO 65243\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer Social Icons-->\r\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Around the Web</h4>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-dribbble\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer About Text-->\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">About Freelancer</h4>\r\n");
      out.write("                        <p class=\"lead mb-0\">\r\n");
      out.write("                            Freelance is a free to use, MIT licensed Bootstrap theme created by\r\n");
      out.write("                            <a href=\"http://startbootstrap.com\">Start Bootstrap</a>\r\n");
      out.write("                            .\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Copyright Section-->\r\n");
      out.write("        <div class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("            <div class=\"container\"><small>Copyright &copy; Your Website 2023</small></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      ");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	function login(){\r\n");
      out.write("		//alert('눌림');\r\n");
      out.write("		//alert($('#userid').val());\r\n");
      out.write("		console.log($('#userid').val());\r\n");
      out.write("		console.log($('#userpw').val());		\r\n");
      out.write("		if($('#userid').val()==''){\r\n");
      out.write("			alert('아이디를 입력해주세요');\r\n");
      out.write("			$('#userid').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}else if($('#userpw').val()==''){\r\n");
      out.write("			alert('pw를 입력해주세요');\r\n");
      out.write("			$('#userpw').focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		/* 여기까지 도착함 코드 스택이. => 아이디 비밀번호가 입력이 된 상태 */\r\n");
      out.write("		// get방식으로 ajax비동기 통신을 통해서 servlet으로 데이터 전송.(url) : 페이지 새로고침 없이 데이터만 요청.\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:'post',	   // 요청 방식\r\n");
      out.write("			url: 'login.mem', // 요청 URL\r\n");
      out.write("			data: {id:$('#userid').val(), pw:$('#userpw').val()  } , // 요청시 보낼 파라메터 설정\r\n");
      out.write("			success: function ( response ){ //성공시 실행할 함수\r\n");
      out.write("				if(response == ''){\r\n");
      out.write("					alert('아이디 또는 비밀번호 CAPS LOCK 상태 확인하세요')\r\n");
      out.write("				}else{\r\n");
      out.write("					alert('aaaa' + response);\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			}, error: function (req,text) { //성공시 실행할 함수\r\n");
      out.write("				alert(text + ':'+req.status);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
